spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:godeye}
    username: ${POSTGRES_USER:godeye}
    password: ${POSTGRES_PASSWORD:123ABCdef*}
    hikari:
      transaction-isolation: TRANSACTION_REPEATABLE_READ