openapi: 3.1.0
info:
  title: redline
  description: 进销存系统服务接口文档
  version: 0.0.1
servers:
  - url: http://localhost:8080
tags:
  - name: user
    description: 用户

paths:
  /user:
    get:
      tags:
        - user
      summary: 用户列表
      description: 用户列表
      operationId: listUsers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BasicUser'
components:
  schemas:
    BasicUser:
      type: object
      required:
        - id
        - username
        - nickname
        - createdAt
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        nickname:
          type: string
        createdAt:
          type: integer
          format: int64
    Error:
      description: 错误信息
      type: object
      required:
        - type
      properties:
        type:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
          format: int32
        error:
          type: string
        path:
          type: string

  responses:
    BadRequestResponse:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'